language: python
dist: xenial
sudo: required
env:
python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"
install:
    - "make setup"
    - "pip install ."
script:
    - "make test"
after_success:
    - "codecov"
matrix:
    allow_failures:
        - python: "3.8-dev"
    include:
        - python: "pypy3.5"
          install:
              - "pip install aiounittest coverage"
          after_success:
              - "true"
        - python: "3.6"
          env: LINTING=true PERF=true
          script:
              - "make lint test perf"
